In [27]:
import numpy as np

n=int(input("Enter the side length of Magic Square (ODD): "))
matrix = np.zeros((n,n), dtype=int)

def top(row):
    row-=1
    if (row<0): 
        return (n-1)
    return row
    
def right(col):
    return (col+1)%n

def bottom(row):
    return (row+1)%n

def fillMatrix(row, col, count):
    if(count>n**2):
        return
    if (matrix[top(row)][right(col)] == 0):
        row=top(row)
        col=right(col)
    else:
        row=bottom(row)
    
    matrix[row][col]=count    
    fillMatrix(row, col, count+1)

matrix[0][n//2]=1   #Placing 1 in matrix
fillMatrix(0, n//2, 2)

print("\nMAGIC SQUARE")
print(matrix)

Enter the side length of Magic Square (ODD): 6

MAGIC SQUARE
[[19 27 35  1  9 17]
 [26 34  6  8 16 24]
 [33  5  7 15 23 25]
 [ 4 12 14 22 30 32]
 [11 13 21 29 31  3]
 [18 20 28 36  2 10]]


In [29]:
def checkSum(matrix,n):
    print('sum of row')
    for i in range(n):
        summ =0
        for j in range(n):
            summ = summ+matrix[i][j]
        print(summ)
    print('sum of col')
    for i in range(n):
        summ =0
        for j in range(n):
            summ = summ+matrix[j][i]
        print(summ)
    print('sum of diag')
    summ =0
    for i in range(n):
        for j in range(n):
            if(i==j):
                summ = summ+matrix[i][j]
    print(summ)
    summ =0
    for i in reversed(range(n)):
        for j in reversed(range(n)):
            if(i==j):
                summ = summ+matrix[i][j]
    print(summ)
checkSum(matrix,6)

sum of row
108
114
108
114
108
114
sum of col
111
111
111
111
111
111
sum of diag
123
123
