In [1]:
import numpy as np
board=[ [0,3,0,0,8,0,0,0,1],
              [0,0,7,4,0,1,0,5,0],
              [9,0,0,0,5,0,2,0,0],
              [0,0,2,0,0,5,0,1,0],
              [3,0,0,2,1,0,5,0,0],
              [5,9,0,0,6,0,0,0,2],
              [0,0,6,5,0,2,0,0,0],
              [0,0,9,6,0,0,0,2,7],
              [0,0,0,0,0,8,0,6,5]
             
    ]
board

[[0, 3, 0, 0, 8, 0, 0, 0, 1],
 [0, 0, 7, 4, 0, 1, 0, 5, 0],
 [9, 0, 0, 0, 5, 0, 2, 0, 0],
 [0, 0, 2, 0, 0, 5, 0, 1, 0],
 [3, 0, 0, 2, 1, 0, 5, 0, 0],
 [5, 9, 0, 0, 6, 0, 0, 0, 2],
 [0, 0, 6, 5, 0, 2, 0, 0, 0],
 [0, 0, 9, 6, 0, 0, 0, 2, 7],
 [0, 0, 0, 0, 0, 8, 0, 6, 5]]

In [2]:
def possible(row,col,n):
    global board
    for i in range(0,9):
        if board[row][i]==n:
            return False
    for i in range(0,9):
        if board[i][col]==n:
            return False
    nRowGrid =(col//3)*3
    nColGrid =(row//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if board[nColGrid+i][nRowGrid+j]==n:
                return False
    return True
    

In [3]:
possible(0,2,1)

False

In [4]:
def solve():
    global board
    for row in range(9):
        for col in range(9):
            if board[row][col]==0:
                for n in range (1,10):
                    if possible(row,col,n):
                        board[row][col]=n
                        solve()
                        board[row][col]=0
                return

    print(np.matrix(board))
    input('More Solution')
            

In [5]:
solve()

[[2 3 5 7 8 9 6 4 1]
 [6 8 7 4 2 1 3 5 9]
 [9 1 4 3 5 6 2 7 8]
 [4 7 2 9 3 5 8 1 6]
 [3 6 8 2 1 7 5 9 4]
 [5 9 1 8 6 4 7 3 2]
 [1 4 6 5 7 2 9 8 3]
 [8 5 9 6 4 3 1 2 7]
 [7 2 3 1 9 8 4 6 5]]


KeyboardInterrupt: Interrupted by user