In [1]:
import numpy as np

In [2]:
m = np.array([[2,0,3],[1,0,0],[0,0,1]])
m

array([[2, 0, 3],
       [1, 0, 0],
       [0, 0, 1]])

In [3]:
def checkPossibleFit(row, col, matrix):
    for i in range(1,4):
        if( i not in matrix[row]):
                if( i not in matrix[:,col]):
                    matrix[row][col]=i
                    
#     print(matrix[col])

In [4]:
def solver(matrix):
#     print(matrix)
    for i in range(3):
        for j in range(3):
            val = matrix[i][j]
            if(val==0):
                print(i,j, '=>' ,matrix[i][j])
                checkPossibleFit(i,j,matrix)
                

    print(matrix)

In [5]:
solver(m)

0 1 => 0
1 1 => 0
1 2 => 0
2 0 => 0
2 1 => 0
[[2 1 3]
 [1 3 2]
 [3 2 1]]
