In [1]:
import numpy as np
import sys

In [2]:
def possibleMove(i,j,n):
    arr=[]
    if((i-2)>=0 and (j+1)<n):
        arr.append([i-2,j+1])
    if((i-1)>=0 and (j+2)<n):
        arr.append([(i-1),(j+2)])
    if((i+1)<n and (j+2)<n):
        arr.append([(i+1),(j+2)])
    if((i+2)<n and (j+1)<n):
        arr.append([(i+2),(j+1)])
    if((i+2)<n and (j-1)>=0):
        arr.append([(i+2),(j-1)])
    if((i+1)<n and (j-2)>=0):
        arr.append([(i+1),(j-2)])
    if((i-1)>=0 and (j-2)>=0):
        arr.append([(i-1),(j-2)])
    if((i-2)>=0 and (j-1)>=0):
        arr.append([(i-2),(j-1)])
    return arr

In [3]:
# def solve(board,n,i,j,cnt):
#     m=possibleMove(i,j,n)
# #     print(m)
#     if(i<0 or j<0 or i>=n or j>=n):
#         return
#     if(board[i][j]!=0):
#         return
#     if(cnt==(n*n)):
#         board[i][j]=cnt
#         return 
    
#     board[i][j]=cnt
#     m=possibleMove(i,j,n)
# #     print(m)
    
#     solve(board,n,m[0][0],m[0][1],cnt+1)
#     solve(board,n,m[1][0],m[1][1],cnt+1)
#     solve(board,n,m[2][0],m[2][1],cnt+1)
#     solve(board,n,m[3][0],m[3][1],cnt+1)
#     solve(board,n,m[4][0],m[4][1],cnt+1)
#     solve(board,n,m[5][0],m[5][1],cnt+1)
#     solve(board,n,m[6][0],m[6][1],cnt+1)
#     solve(board,n,m[7][0],m[7][1],cnt+1)
#     solve(board,n,m[8][0],m[8][1],cnt+1)
#     board[i][j]=0
    
#     return
         
# n=9
# cnt=1
# i=0
# j=0
# board=np.zeros((n,n),dtype=int)
# solve(board,n,i,j,cnt)

In [4]:
def getUniquePosition(moved,Pp):
    for i in moved:
        if(Pp.count(i)>0):
            Pp.remove(i)
    return Pp

In [5]:
P=possibleMove(4,4,9)
print(P)
getUniquePosition([[1, 2], [2, 5], [1, 6]],P)

[[2, 5], [3, 6], [5, 6], [6, 5], [6, 3], [5, 2], [3, 2], [2, 3]]


[[3, 6], [5, 6], [6, 5], [6, 3], [5, 2], [3, 2], [2, 3]]

In [6]:
moved =[]
def getUniquePosition(moved,Pp):
    for i in moved:
        if(Pp.count(i)>0):
            Pp.remove(i)
    return Pp
    
    
def solve(board,n,i,j,cnt):
    global moved
    print(moved)
    m=[]
    if(cnt>n*n):
        sys.exit()
    m=getUniquePosition(moved,possibleMove(i,j,n))
    if(len(m)==0):
        temp=moved.pop()
        r2=temp[0]
        c2=temp[1]
        board[r2][c2]=0
        temp1=moved[-1]
        temp2=possibleMove(temp1[0],temp1[1],n)
        if(temp2.count(temp)>0):
            temp2.remove(temp)
        solve(board,n,temp2[0][0],temp2[0][1],cnt)
        
    idxs=m[0]
    print(m)
    r=idxs[0]
    c=idxs[1]
    if(board[r][c]!=0):
#         print(m,"before")
        idsx=m[0]
#         print(m,"after")
#         print(idsx)
        r1=idsx[0]
        c1=idsx[1]
#         print(r1,c1,"printed")
        board[r1][c1]=cnt
        moved.append([r1,c1])
        print(board)
        solve(board,n,r1,c1,cnt+1)
        board[r1][c1]=0
    if(board[r][c]==0):
        board[r][c]=cnt
        moved.append([r,c])
        print(board)
        if(moved.count([0,0])>0):
            print("yes")
        solve(board,n,r,c,cnt+1)
        board[r][c]=0
#         print(board)

         
n=8
cnt=1
i=0
j=0
board=np.zeros((n,n),dtype=int)
board[i][j]=cnt
solve(board,n,i,j,cnt+1)

[]
[[1, 2], [2, 1]]
[[1 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1, 2]]
[[0, 4], [2, 4], [3, 3], [3, 1], [2, 0], [0, 0]]
[[1 0 0 0 3 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1, 2], [0, 4]]
[[1, 6], [2, 5], [2, 3]]
[[1 0 0 0 3 0 0 0]
 [0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1, 2], [0, 4], [1, 6]]
[[3, 7], [3, 5], [2, 4]]
[[1 0 0 0 3 0 0 0]
 [0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1, 2], [0, 4], [1, 6], [3, 7]]
[[5, 6], [4, 5], [2, 5]]
[[1 0 0 0 3 0 0 0]
 [0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1, 2]

SystemExit: 

C:\Users\thero\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
moved=[]
def getUniquePosition(moved,Pp):
    for i in moved:
        if(Pp.count(i)>0):
            Pp.remove(i)
    return Pp
    
    
def solve(board,n,i,j,cnt):
    global moved
#     print(board)
    m=[]
    if(cnt>n*n):
        sys.exit()
    m=getUniquePosition(moved,possibleMove(i,j,n))
    print(m," available move for ",cnt )
    if(len(m)==0):
        temp=moved.pop()
        r2=temp[0]
        c2=temp[1]
        board[r2][c2]=0
        temp1=moved[-1]
        temp2=possibleMove(temp1[0],temp1[1],n)
        if(temp2.count(temp)>0):
            temp2.remove(temp)
        print(temp1,"available moves for cnt")
        solve(board,n,temp2[0][0],temp2[0][1],cnt)
        
    idxs=m[0]
#     print(m)
    r=idxs[0]
    c=idxs[1]
    if(board[r][c]!=0):
#         print(m,"before")
        idsx=m[0]
#         print(m,"after")
#         print(idsx)
        r1=idsx[0]
        c1=idsx[1]
#         print(r1,c1,"printed")
        board[r1][c1]=cnt
        moved.append([r1,c1])
        print(board,"Not equals zero")
        solve(board,n,r1,c1,cnt+1)
        board[r1][c1]=0
    if(board[r][c]==0):
        board[r][c]=cnt
        moved.append([r,c])
        print(board,"equals zero value put =>",cnt)
#         if(moved.count([0,0])>0):
#             print("yes")
        solve(board,n,r,c,cnt+1)
        board[r][c]=0
#         print(board)

         
n=8
cnt=1
i=0
j=0
board=np.zeros((n,n),dtype=int)
board[i][j]=cnt
solve(board,n,i,j,cnt+1)

In [ ]:
possibleMove(1,0,9)

In [7]:
import numpy as np
import sys
row=[2,1,-1,-2,-2,-1,1,2,2]
col=[1,2,2,1,-1,-2,-2,-1,1]

def vaildMove(i,j):
    if(i<0 or j<0 or i>=n or j>=n):
        return False
    return True
def solveForKTour(board,i,j,n,cnt):
    board[i][j]=cnt
    if(cnt>=n*n):
        print(board)
        board[i][j]=0
#         sys.exit()
        return board
    for k in range(8):
        nx=i+row[k]
        ny=j+col[k]
        if(vaildMove(nx,ny) and board[nx][ny]==0):
            solveForKTour(board,nx,ny,n,cnt+1)
    board[i][j]=0      
    
n=8
cnt=1
i=0
j=0
board=np.zeros((n,n),dtype=int)
print(solveForKTour(board,i,j,n,cnt))    
    


[[ 1 60 39 34 31 18  9 64]
 [38 35 32 61 10 63 30 17]
 [59  2 37 40 33 28 19  8]
 [36 49 42 27 62 11 16 29]
 [43 58  3 50 41 24  7 20]
 [48 51 46 55 26 21 12 15]
 [57 44 53  4 23 14 25  6]
 [52 47 56 45 54  5 22 13]]
[[ 1 50 45 62 31 18  9 64]
 [46 61 32 49 10 63 30 17]
 [51  2 47 44 33 28 19  8]
 [60 35 42 27 48 11 16 29]
 [41 52  3 34 43 24  7 20]
 [36 59 38 55 26 21 12 15]
 [53 40 57  4 23 14 25  6]
 [58 37 54 39 56  5 22 13]]
[[ 1 60 45 48 31 18  9 64]
 [46 49 32 61 10 63 30 17]
 [59  2 47 44 33 28 19  8]
 [50 35 42 27 62 11 16 29]
 [41 58  3 34 43 24  7 20]
 [36 51 38 55 26 21 12 15]
 [57 40 53  4 23 14 25  6]
 [52 37 56 39 54  5 22 13]]
[[ 1 60 57 44 31 18  9 64]
 [58 43 32 61 10 63 30 17]
 [33  2 59 56 45 28 19  8]
 [42 47 54 27 62 11 16 29]
 [53 34  3 46 55 24  7 20]
 [48 41 50 37 26 21 12 15]
 [35 52 39  4 23 14 25  6]
 [40 49 36 51 38  5 22 13]]
[[ 1 60 43 48 31 18  9 64]
 [44 49 32 61 10 63 30 17]
 [59  2 45 42 47 28 19  8]
 [50 33 40 27 62 11 16 29]
 [39 58  3 46 41 24  7 2

KeyboardInterrupt: 