Building a Static matrix

In [1]:
# import numpy as np
# matrix = np.array([ [[0,5,2],[1,6,0],[0,4,9]], [[0,0,6],[9,0,0],[8,0,3]],   [[0,0,0],[0,0,4],[6,2,0]] ,
                   
#                    [[4,0,0],[0,8,3],[0,0,1]],  [[0,0,0],[2,0,1],[0,0,0]],   [[8,0,0],[5,9,0],[0,0,2]],
                   
#                    [[0,9,7],[2,0,0],[0,0,0]],  [[3,0,5],[0,0,9],[1,0,0]],   [[2,4,0],[0,5,6],[9,7,0]]
#                                                ])
# # matrix.reshape((9,3,-1))
# print(matrix)

In [2]:
import numpy as np
import random
matrix = np.array([ [0,5,2,0,0,6,0,0,0],
                    [1,6,0,9,0,0,0,0,4],
                    [0,4,9,8,0,3,6,2,0],
                    [4,0,0,0,0,0,8,0,0],
                    [0,8,3,2,0,1,5,9,0],
                    [0,0,1,0,0,0,0,0,2],
                    [0,9,7,3,0,5,2,4,0],
                    [2,0,0,0,0,9,0,5,6],
                    [0,0,0,1,0,0,9,7,0],
                   
                   
                   
                                               ])
# matrix.reshape((9,3,-1))
print(matrix)

[[0 5 2 0 0 6 0 0 0]
 [1 6 0 9 0 0 0 0 4]
 [0 4 9 8 0 3 6 2 0]
 [4 0 0 0 0 0 8 0 0]
 [0 8 3 2 0 1 5 9 0]
 [0 0 1 0 0 0 0 0 2]
 [0 9 7 3 0 5 2 4 0]
 [2 0 0 0 0 9 0 5 6]
 [0 0 0 1 0 0 9 7 0]]


Function to generate random number

In [3]:
def RanNumGen():
    return random.randint(1,10)

Check if Grid Contains same number

In [ ]:
def DuplicateCheck(M):
    a = []
    for i in range(3):
        for j in range(3):
            if Matrix[i][j] is not in matrix
            

Function to solve the matrix

In [8]:
def GetSolution(Matrix):
    for i in range(9):
        for j in range(9):
            if (i<3 and j<3 and Matrix[i][j]==0):
                Matrix[i][j]=RanNumGen()
            DuplicateCheck(Matrix)
                
            
    print(Matrix)

In [9]:
GetSolution(matrix)

[[6 5 2 0 0 6 0 0 0]
 [1 6 6 9 0 0 0 0 4]
 [4 4 9 8 0 3 6 2 0]
 [4 0 0 0 0 0 8 0 0]
 [0 8 3 2 0 1 5 9 0]
 [0 0 1 0 0 0 0 0 2]
 [0 9 7 3 0 5 2 4 0]
 [2 0 0 0 0 9 0 5 6]
 [0 0 0 1 0 0 9 7 0]]
