In [1]:
import numpy as np 

In [2]:
board = np.array([[-1,-1,-1],[-1,-1,-1],[-1,-1,-1]])
board

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [6]:
def TTT(board):
    board[1][1]=1
    a=int(input('Enter box number for putting o in Board :-'))
    if(a<9 and a>0):
        print('ok')
    else:
        print('error')
    
    print(board)
    

In [7]:
TTT(board)

Enter box number for putting o in Board :-3
ok
[[-1 -1 -1]
 [-1  1 -1]
 [-1 -1 -1]]
