In [1]:
import numpy as np
m = np.array([[0,1,0],[0,0,0],[0,0,0]])
m

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [2]:
def solve(row,col,matrix):
    put=1
    cRow=row
    cCol=col

    for i in range(8):
        print(matrix)
        nRow=cRow-1
        nCol=cCol+1
        print("in")
        print(nRow,nCol)
        if(nRow>=0 and nCol<3):
            print("if")
            if(matrix[nRow][nCol]==0):
                matrix[nRow][nCol]=put+1
#                 nRow=nRow-1
#                 nCol=nCol+1
                cRow=nRow
                cCol=nCol
                put=put+1
                continue
            else:
                nRow=cRow+1
                if(nRow>=0 and nRow<3 and nCol<3):
                    matrix[nRow][nCol]=put+1
                    nRow=nRow-1
                    nCol=nCol+1
                    put=put+1
                    continue
                else:
                    nRow=nRow%3
                    matrix[nRow][nCol]=put+1
                    nRow=nRow-1
                    nCol=nCol+1
                    put=put+1
                    continue
        elif(nRow<0 and nCol<3):
            nRow=nRow%3
            ncol=nCol%3
            if(matrix[nRow][nCol]==0):
                matrix[nRow][nCol]=put+1
#                 nRow=nRow-1 
#                 nCol=nCol+1
                cRow=nRow
                cCol=nCol
                put=put+1
                continue
            else:
                nRow=cRow+1
                if(nRow>=0 and nRow<3 and nCol<3):
                    matrix[nRow][nCol]=put+1
#                     nRow=nRow-1
#                     nCol=nCol+1
                    cRow=nRow
                    cCol=nCol
                    put=put+1
                    continue
                else:
                    matrix[nRow][nCol]=put+1
                    nRow=nRow-1
                    nCol=nCol+1
                    put=put+1
                    continue
        elif(nRow>=0 and nCol>=3):
            nCol=nCol%3
            print(nRow,nCol)
            if(matrix[nRow][nCol]==0):
                matrix[nRow][nCol]=put+1
#                 nRow=nRow-1 
#                 nCol=nCol+1
                cRow=nRow
                cCol=nCol
                put=put+1
                continue
            else:
                nRow=row+1
                if(nRow>=0 and nRow<3 and nCol<3):
                    matrix[nRow][nCol]=put+1
                    nRow=nRow-1
                    nCol=nCol+1
                    put=put+1
                    continue
                else:
                    matrix[nRow][nCol]=put+1
                    nRow=nRow-1
                    nCol=nCol+1
                    put=put+1
                    continue

In [3]:
print(m)
solve(0,1,m)

[[0 1 0]
 [0 0 0]
 [0 0 0]]
[[0 1 0]
 [0 0 0]
 [0 0 0]]
in
-1 2
[[0 1 0]
 [0 0 0]
 [0 0 2]]
in
1 3
1 0
[[0 1 0]
 [3 0 0]
 [0 0 2]]
in
0 1
if
[[0 1 0]
 [3 0 0]
 [0 4 2]]
in
0 1
if
[[0 1 0]
 [3 0 0]
 [0 5 2]]
in
0 1
if
[[0 1 0]
 [3 0 0]
 [0 6 2]]
in
0 1
if
[[0 1 0]
 [3 0 0]
 [0 7 2]]
in
0 1
if
[[0 1 0]
 [3 0 0]
 [0 8 2]]
in
0 1
if


In [4]:
def solve(n):
    m = [ [0 for x in range(n)] for y in range(n) ]
    row = 0
    col = 1
    num=2
    m[row][col]=1
    for i in range(n*n-1):
        if(row-1<0 and col+1<n):
            if(m[n-1][col+1]==0):
                m[n-1][col+1]=num
                num=num+1
                row=n-1
                col=col+1
            else:
                if(row+1<n):
                    m[row+1][col]=num
                    num=num+1
                    row=row+1
                    col=col
                else:
                    m[0][col]=num
                    num=num+1
                    row=row+1
                    col=col
        elif(row-1>=0 and col+1<n):
            if(m[row-1][col+1]==0):
                m[row-1][col+1]=num
                num=num+1
                row=row-1
                col=col+1
            else:
                if(row+1<n):
                    m[row+1][col]=num
                    num=num+1
                    row=row+1
                    col=col
                else:
                    m[0][col]=num
                    num=num+1
                    row=row+1
                    col=col
        elif(row-1>=0 and col+1>=n):
            if(m[row-1][0]==0):
                m[row-1][0]=num
                num=num+1
                row=row-1
                col=0
            else:
                if(row+1<n):
                    m[row+1][col]=num
                    num=num+1
                    row=row+1
                    col=col
                else:
                    m[0][col]=num
                    num=num+1
                    row=row+1
                    col=col
        elif(row-1<0 and col+1>=n):
            if(m[n-1][0]==0):
                m[n-1][0]=num
                num=num+1
                row=n-1
                col=0
            else:
                if(row+1<n):
                    m[row+1][col]=num
                    num=num+1
                    row=row+1
                    col=col
                else:
                    m[0][col]=num
                    num=num+1
                    row=row+1
                    col=col
        
            
    
    print(np.matrix(m))

In [5]:
solve(3)

[[8 1 6]
 [3 5 7]
 [4 9 2]]
