In [1]:
import numpy as np
m = np.array([[0,3,0,0,8,0,0,0,1],
              [0,0,7,4,0,1,0,5,0],
              [9,0,0,0,5,0,2,0,0],
              [0,0,2,0,0,5,0,1,0],
              [3,0,0,2,1,0,5,0,0],
              [5,9,0,0,6,0,0,0,2],
              [0,0,6,5,0,2,0,0,0],
              [0,0,9,6,0,0,0,2,7],
              [0,0,0,0,0,8,0,6,5]
             ])
m

array([[0, 3, 0, 0, 8, 0, 0, 0, 1],
       [0, 0, 7, 4, 0, 1, 0, 5, 0],
       [9, 0, 0, 0, 5, 0, 2, 0, 0],
       [0, 0, 2, 0, 0, 5, 0, 1, 0],
       [3, 0, 0, 2, 1, 0, 5, 0, 0],
       [5, 9, 0, 0, 6, 0, 0, 0, 2],
       [0, 0, 6, 5, 0, 2, 0, 0, 0],
       [0, 0, 9, 6, 0, 0, 0, 2, 7],
       [0, 0, 0, 0, 0, 8, 0, 6, 5]])

In [2]:
# def checkForGrid(row,col,matrix):
#     startRow=row-row%3
#     startCol=col-col%3
#     if(startRow<3):
#         for i in range(3):
            
#     if(startRow>2 && startRow<6):
#         for i in range(3,6):
#     if(startRow >6):
#         for i in range(6,9):
    
#     print(startRow,startCol)

In [3]:
def checkPossibleFit(row, col, matrix):
    newRow=(row//3)
    newCol=(col//3)
    temp =[]
    if(newRow>1):
        newRow=6
    if(newRow>0):
        newRow=3
    if(newCol>1):
        newCol=6
    if(newCol>0):
        newCol=3
    for i in range(newRow,newRow+3):
        for j in range(newCol,newCol+3):    
            temp.append(matrix[i][j])
    
    for i in range(1,9):
        if(i not in matrix[row]):
                if( i not in matrix[:,col]):
                    if(i not in temp):
                        matrix[row][col]=i
                        return False
                    return False
                return False
            
#     checkForGrid(row, col ,matrix)

In [4]:
def solve(matrix):
    print(matrix)
    for i in range(9):
        for j in range(9):
            val = matrix[i][j]
            if(val==0):
                print(i,j, '=>' ,matrix[i][j])
                checkPossibleFit(i,j,matrix)
                    
#                 solve(matrix)
    print(matrix)

In [5]:
solve(m)

[[0 3 0 0 8 0 0 0 1]
 [0 0 7 4 0 1 0 5 0]
 [9 0 0 0 5 0 2 0 0]
 [0 0 2 0 0 5 0 1 0]
 [3 0 0 2 1 0 5 0 0]
 [5 9 0 0 6 0 0 0 2]
 [0 0 6 5 0 2 0 0 0]
 [0 0 9 6 0 0 0 2 7]
 [0 0 0 0 0 8 0 6 5]]
0 0 => 0
0 2 => 0
0 3 => 0
0 5 => 0
0 6 => 0
0 7 => 0
1 0 => 0
1 1 => 0
1 4 => 0
1 6 => 0
1 8 => 0
2 1 => 0
2 2 => 0
2 3 => 0
2 5 => 0
2 7 => 0
2 8 => 0
3 0 => 0
3 1 => 0
3 3 => 0
3 4 => 0
3 6 => 0
3 8 => 0
4 1 => 0
4 2 => 0
4 5 => 0
4 7 => 0
4 8 => 0
5 2 => 0
5 3 => 0
5 5 => 0
5 6 => 0
5 7 => 0
6 0 => 0
6 1 => 0
6 4 => 0
6 6 => 0
6 7 => 0
6 8 => 0
7 0 => 0
7 1 => 0
7 4 => 0
7 5 => 0
7 6 => 0
8 0 => 0
8 1 => 0
8 2 => 0
8 3 => 0
8 4 => 0
8 6 => 0
[[2 3 4 0 8 0 0 0 1]
 [0 0 7 4 2 1 3 5 6]
 [9 1 0 3 5 0 2 0 0]
 [0 0 2 0 3 5 4 1 0]
 [3 4 0 2 1 0 5 0 0]
 [5 9 1 0 6 0 0 0 2]
 [0 0 6 5 0 2 0 0 0]
 [0 0 9 6 0 0 0 2 7]
 [0 0 0 0 0 8 0 6 5]]
